version: 0.2

env:
  variables:
    PROJECT: ClassLibraryProject
    DOTNET_FRAMEWORK: 4.8
phases:
  build:
    commands:
      - nuget restore
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v$env:DOTNET_FRAMEWORK" $env:PROJECT'